use std::collections::HashMap;

lazy_static! {
    pub static ref MIMES: HashMap<&'static str, &'static str> = {
        let mut map = HashMap::new();
        map.insert("aac", "audio/aac");
        map.insert("abw", "application/x-abiword");
        map.insert("arc", "application/octet-stream");
        map.insert("avi", "video/x-msvideo");
        map.insert("azw", "application/vnd.amazon.ebook");
        map.insert("bin", "application/octet-stream");
        map.insert("bz", "application/x-bzip");
        map.insert("bz2", "application/x-bzip2");
        map.insert("csh", "application/x-csh");
        map.insert("css", "text/css");
        map.insert("csv", "text/csv");
        map.insert("doc", "application/msword");
        map.insert("epub", "application/epub+zip");
        map.insert("gif", "image/gif");
        map.insert("html", "text/html");
        map.insert("ico", "image/x-icon");
        map.insert("ics", "text/calendar");
        map.insert("jar", "application/java-archive");
        map.insert("jpg", "image/jpeg");
        map.insert("js", "application/javascript");
        map.insert("json", "application/json");
        map.insert("midi", "audio/midi");
        map.insert("mpeg", "video/mpeg");
        map.insert("mpkg", "application/vnd.apple.installer+xml");
        map.insert("odp", "application/vnd.oasis.opendocument.presentation");
        map.insert("ods", "application/vnd.oasis.opendocument.spreadsheet");
        map.insert("odt", "application/vnd.oasis.opendocument.text");
        map.insert("oga", "audio/ogg");
        map.insert("ogv", "video/ogg");
        map.insert("ogx", "application/ogg");
        map.insert("pdf", "application/pdf");
        map.insert("ppt", "application/vnd.ms-powerpoint");
        map.insert("rar", "application/x-rar-compressed");
        map.insert("rtf", "application/rtf");
        map.insert("sh", "application/x-sh");
        map.insert("svg", "image/svg+xml");
        map.insert("swf", "application/x-shockwave-flash");
        map.insert("tar", "application/x-tar");
        map.insert("tiff", "image/tiff");
        map.insert("ttf", "font/ttf");
        map.insert("vsd", "application/vnd.visio");
        map.insert("wav", "audio/x-wav");
        map.insert("weba", "audio/webm");
        map.insert("webm", "video/webm");
        map.insert("webp", "image/webp");
        map.insert("woff", "font/woff");
        map.insert("woff2", "font/woff2");
        map.insert("xhtml", "application/xhtml+xml");
        map.insert("xls", "application/vnd.ms-excel");
        map.insert("xml", "application/xml");
        map.insert("xul", "application/vnd.mozilla.xul+xml");
        map.insert("zip", "application/zip");
        map.insert("3gp", "video/3gpp");
        map
    };
}
