name: Rust

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Kill tachyon
      run:  if ! kill -9 $(cat logs/pid) > /dev/null 2>&1; then echo "NO PID" > &2 fi
    - name: Run tachyon
      run: cargo run 10.166.0.2:5001
